FROM node:18.17.1-alpine3.18

# Set working directory
WORKDIR /app

# Install development dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Create required directories
RUN mkdir -p uploads/projects uploads/certificates/images uploads/certificates/files uploads/users logs

# Expose port
EXPOSE 5000

# Start the application in development mode
CMD ["npm", "run", "dev"]